### ISSUE TITLE
请问有没有详细的使用手册，数据集路径啥的是和mmdetection一样的么，本人小白，看到大佬的框架非常佩服，非常感谢

### ISSUE THREAD

**Issue by hu-wei-carrzy** [Xuyihaoby/rotate_detection#1]

**Comment by Xuyihaoby** [comment]
是的，数据路径都是差不多的。基本上就是基于mmedetection修改出来的。

**Comment by hu-wei-carrzy** [comment]
非常感谢您的回复！
但是我在按照环境配置后出现一些问题
导入报错











------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月4日(星期二) 晚上6:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xuyihaoby/rotate_detection] 请问有没有详细的使用手册，数据集路径啥的是和mmdetection一样的么，本人小白，看到大佬的框架非常佩服，非常感谢 (Issue #1)





 
是的，数据路径都是差不多的。基本上就是基于mmedetection修改出来的。

**Comment by Xuyihaoby** [comment]
方便提供相关导入报错信息吗？

**Comment by hu-wei-carrzy** [comment]
以下是我的报错




/home/giant/miniconda3/envs/hw_rotate/bin/python&nbsp;/media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py&nbsp;/media/giant/Data/WorkSpace/hw/rotate_detection-main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x.py&nbsp;/media/giant/Data/WorkSpace/hw/rotate_detection-main/workdirs/oriented_rcnn/oriented_rcnn_r50_fpn_1x
Traceback&nbsp;(most&nbsp;recent&nbsp;call&nbsp;last):
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py",&nbsp;line&nbsp;15,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;mmdet.apis&nbsp;import&nbsp;set_random_seed,&nbsp;train_detector
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/__init__.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.inference&nbsp;import&nbsp;(async_inference_detector,&nbsp;inference_detector,
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/inference.py",&nbsp;line&nbsp;10,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;mmdet.core&nbsp;import&nbsp;get_classes
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/__init__.py",&nbsp;line&nbsp;2,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.bbox&nbsp;import&nbsp;*&nbsp;&nbsp;#&nbsp;noqa:&nbsp;F401,&nbsp;F403
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/bbox/__init__.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.assigners&nbsp;import&nbsp;(AssignResult,&nbsp;BaseAssigner,&nbsp;CenterRegionAssigner,
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/bbox/assigners/__init__.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.approx_max_iou_assigner&nbsp;import&nbsp;ApproxMaxIoUAssigner
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/bbox/assigners/approx_max_iou_assigner.py",&nbsp;line&nbsp;4,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;..iou_calculators&nbsp;import&nbsp;build_iou_calculator
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/bbox/iou_calculators/__init__.py",&nbsp;line&nbsp;3,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.riou2d_calculator&nbsp;import&nbsp;RBboxOverlaps2D,&nbsp;ConvexOverlaps2D,&nbsp;rbbox_overlaps,&nbsp;rbbox_overlaps_v2,&nbsp;rbbox_overlaps_v3
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/core/bbox/iou_calculators/riou2d_calculator.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;mmdet.ops&nbsp;import&nbsp;rbbox_iou_iof,&nbsp;obb_overlaps
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/ops/__init__.py",&nbsp;line&nbsp;5,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.polygon_geo&nbsp;import&nbsp;polygon_iou
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/ops/polygon_geo/__init__.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.polygon_geo&nbsp;import&nbsp;polygon_iou
&nbsp;&nbsp;File&nbsp;"/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/ops/polygon_geo/polygon_geo.py",&nbsp;line&nbsp;1,&nbsp;in&nbsp;<module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from&nbsp;.&nbsp;import&nbsp;polygon_geo_cpu
ImportError:&nbsp;cannot&nbsp;import&nbsp;name&nbsp;'polygon_geo_cpu'&nbsp;from&nbsp;partially&nbsp;initialized&nbsp;module&nbsp;'mmdet.ops.polygon_geo'&nbsp;(most&nbsp;likely&nbsp;due&nbsp;to&nbsp;a&nbsp;circular&nbsp;import)&nbsp;(/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/ops/polygon_geo/__init__.py)

Process&nbsp;finished&nbsp;with&nbsp;exit&nbsp;code&nbsp;1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月4日(星期二) 晚上7:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xuyihaoby/rotate_detection] 请问有没有详细的使用手册，数据集路径啥的是和mmdetection一样的么，本人小白，看到大佬的框架非常佩服，非常感谢 (Issue #1)





 
方便提供相关导入报错信息吗？

**Comment by Xuyihaoby** [comment]
是否有运行以下命令去编译算子   pip install -v -e . # or "python setup.py develop"？

**Comment by hu-wei-carrzy** [comment]
有运行命令python setup.py develop

**Comment by Xuyihaoby** [comment]
成功编译了？

**Comment by hu-wei-carrzy** [comment]
我重头再按教程来一次

**Comment by Xuyihaoby** [comment]
没事儿，如果实在不太好编译的话，这里也更加推荐原作者版或者mmrotate，我在reference下也已经贴明链接 ：）

**Comment by hu-wei-carrzy** [comment]
我之前用的就是mmrotate

**Comment by hu-wei-carrzy** [comment]
conda create -n hw-rotate python=3.7 -y 
conda activate hw-rotate
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install mmcv-full==1.2.5 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7.0/index.html
pip install -r requirements/build.txt
 python setup.py develop
 
 
 /home/giant/miniconda3/envs/hw-rotate/bin/python /media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/configs/ReDet/faster_rcnn_re50_refpn_1x.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/workdirs/ReDet/faster_rcnn_re50_refpn_1x
Traceback (most recent call last):
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/datasets/cityscapes.py", line 16, in <module>
    from .coco import CocoDataset
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/datasets/coco.py", line 21, in <module>
    assert pycocotools.__version__ >= '12.0.2'
AttributeError: module 'pycocotools' has no attribute '__version__'


我尝试  pip install  pycocotools==12.0.2  都没有这个版本

**Comment by hu-wei-carrzy** [comment]
实在抱歉，又来打扰了

**Comment by Xuyihaoby** [comment]
你可以尝试搜索一下，有些可能是mmdetection之前遗留下来的问题；以下是我搜到的结果https://github.com/open-mmlab/mmdetection/issues/3761

**Comment by hu-wei-carrzy** [comment]
是的我也找到了，又有新的缺包，了我的天

**Comment by hu-wei-carrzy** [comment]
/home/giant/miniconda3/envs/hw-rotate/bin/python /media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/configs/ReDet/faster_rcnn_re50_refpn_1x.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/workdirs/ReDet/faster_rcnn_re50_refpn_1x
Traceback (most recent call last):
  File "/home/giant/miniconda3/envs/hw-rotate/lib/python3.7/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/giant/miniconda3/envs/hw-rotate/lib/python3.7/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/tools/train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/datasets/__init__.py", line 16, in <module>
    from .dotav1 import DOTADatasetV1
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/datasets/dotav1.py", line 13, in <module>
    from ..models.utils import transXyxyxyxy2Xyxy
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/models/backbones/__init__.py", line 32, in <module>
    from .involution import RedNet
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/models/backbones/involution.py", line 8, in <module>
    from ..utils.involution_cuda import involution
  File "/media/giant/Data/WorkSpace/hw/rotate_detection-main/mmdet/models/utils/involution_cuda.py", line 9, in <module>
    import cupy
  File "/home/giant/miniconda3/envs/hw-rotate/lib/python3.7/site-packages/cupy/__init__.py", line 37, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libcudart.so.10.1: cannot open shared object file: No such file or directory

Process finished with exit code 1

在build.txt中cupy-cuda101 # note: depend on cuda version，是这个的·原因吗

**Comment by Xuyihaoby** [comment]
是的  你可以选择安装正确的cupy  或者直接在框架下把使用这个包的代码以及相关文件屏蔽

**Comment by hu-wei-carrzy** [comment]
pip install torch==1.7.0+cu110 torchvision==0.8.1+cu110 torchaudio==0.7.0 -f

我下载的是cupy-cuda110，但是还是这个报错

**Comment by Xuyihaoby** [comment]
这个可能需要你自己根据报错情况进行相关调整了

**Comment by hu-wei-carrzy** [comment]
好像配好了，没有导入报错，也可以生成workdirs了，数据集格式好像不太对报错    0.0，今天真是麻烦大哥了

**Comment by hu-wei-carrzy** [comment]
请问我训练之后，提交到dota官网，报错。我之前在mmrotate生成的可以提交成功。
![1E551F7A148D841C5DF1008C97E4C750](https://user-images.githubusercontent.com/116777202/230767771-0c5553eb-ea81-4e73-a6d9-5fea87c036c5.jpg)

好像区别就是图片名称

请问是没有切割test数据集么

**Comment by hu-wei-carrzy** [comment]
我使用
![image](https://user-images.githubusercontent.com/116777202/230768103-22b15e87-afb0-44d9-9a36-cbd90e72c084.png)
但是 没有切割test数据集，这是提交的结果
![image](https://user-images.githubusercontent.com/116777202/230768181-a1eabd39-b842-4657-ad4e-7c52e0f77d0b.png)
请问是要怎么操作额

**Comment by hu-wei-carrzy** [comment]
total_epochs=12
evaluation = dict(interval=24, metric='bbox')
我改成
evaluation = dict(interval=1, metric='mAP')
没有效果，没有每轮训练输出mAP，要怎么才能看到每轮的训练效果呀
麻烦您了。

**Comment by Xuyihaoby** [comment]
在这里生成文件的步骤是分开的，test数据集是切割之后检测再合并的；关于每轮的eval，由于训练效率原因直接将其flag设置为了False，所以这么改是没有效果的。这个框架不像mmrotate那么容易上手，更多的是我自己的一些记录，有些问题可能需要自己阅读源码进行相应的修改：）

**Comment by hu-wei-carrzy** [comment]
#python tools/test.py configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x.py workdirs/oriented_rcnn/oriented_rcnn_r50_fpn_1x/latest.pth --format-only --eval-options submission_dir=workdirs/oriented_rcnn/Task1_results
这是我用的命令，您说的步骤是分开的要怎么操作额，合并要怎么合并额，打扰您了。

**Comment by hu-wei-carrzy** [comment]
还有就是怎么设置才能看到每轮的eval，我好像没有找到您说的将flag设置为了False，麻烦您了。

**Comment by Xuyihaoby** [comment]
测试集同样需要使用DOTA-devkit进行切割，输出使用test输出pkl文件后，利用parse results进行后处理，具体可以参考https://github.com/csuhan/ReDet；在train中把eval默认参数进行修改，之后如若出现一些bug，你可以深入源码尝试自行修改。

**Comment by Xuyihaoby** [comment]
测试集同样需要使用DOTA-devkit进行切割，输出使用test输出pkl文件后，利用parse results进行后处理，具体可以参考[https://github.com/csuhan/ReDet]；在train中把eval默认参数进行修改，之后如若出现一些bug，你可以深入源码尝试自行修改。

**Comment by hu-wei-carrzy** [comment]
在trian.py中修改eval的默认参数，是train_detector中的validate么我修改为true后，在每轮训练的时候就卡在那里不动了
![01879445DCCE466ACF1A835E15F50D74](https://user-images.githubusercontent.com/116777202/231029109-2e104688-287a-4f1a-b198-51827e4038ee.jpg)
![374E287CC39E9FFD669E4485B8B95B21](https://user-images.githubusercontent.com/116777202/231029135-55d211f9-75fb-4f7a-af83-e81b197060fd.jpg)
实在不好意思，尝试了一晚上没有效果，又得打扰一下您了

**Comment by Xuyihaoby** [comment]
在线训练验证确实有可能遇到这样的问题，你可以选择自行更深入的修改，或者离线通过保存每一轮的epoch进行离线验证。
