### ISSUE TITLE
离线验证也还是卡死

### ISSUE THREAD

**Issue by hu-wei-carrzy** [Xuyihaoby/rotate_detection#2]
![9169AF822E0356330575F02537EF390A](https://user-images.githubusercontent.com/116777202/231324899-aa1bed30-60f2-48d2-8060-80fd9a600667.jpg)
我使用的命令是python tools/test.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/configs/oriented_rcnn/oriented_rcnn_r50_fpn_1x.py /media/giant/Data/WorkSpace/hw/rotate_detection-main/workdirs/oriented_rcnn/oriented_rcnn_r50_fpn_1x/latest.pth --eval mAP
请问要怎么解决呀

**Comment by hu-wei-carrzy** [comment]
请问您一般是怎么操作的

**Comment by hu-wei-carrzy** [comment]
我尝试了验证集较小只有几张图片和标签的时候可以得到mAP，但是数据一大，就会卡在pool那里，很奇怪。
终止程序的报错为
![0957D12D9C4D8C3CEEBEE535EA5DC753](https://user-images.githubusercontent.com/116777202/231352920-b0300a16-9a31-45dd-b017-f986458e138f.jpg)
期待您的回复

**Comment by Xuyihaoby** [comment]
这或许仍然是一个待解决的bug，我在本地部分模型使用eval正常
我并没有所有模型都在本地进行eval，更多的是上传服务器进行结果验证

**Comment by Xuyihaoby** [comment]
使用别的常见数据集进行离线验证，可以正常出结果

**Comment by Xuyihaoby** [comment]
like
![image](https://user-images.githubusercontent.com/56283630/231469888-93c9967a-18e5-461c-bf5b-d460d9fd4623.png)

**Comment by hu-wei-carrzy** [comment]
哎还可以这样么，config文件不会不一样么，是[OBBDetection](https://github.com/jbwang1997/OBBDetection)么

**Comment by hu-wei-carrzy** [comment]
![image](https://user-images.githubusercontent.com/116777202/231471615-80d916c3-59de-4f02-b6f3-7f8caf2ceb36.png)
我debug了一下，就是在我标红的框里卡住了。

**Comment by Xuyihaoby** [comment]
不是OBBDetection，我只是拿手边已经训练的模型在切割好的val的数据集进行了一下验证

**Comment by hu-wei-carrzy** [comment]
好的我也去尝试一下

**Comment by Xuyihaoby** [comment]
当然如果你真的遇到困难，无法解决，不妨去也可以选择其他更加用户友好型框架
